version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: gpp-mysql-container
    command: --default-authentication-plugin=mysql_native_password
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - '3306:3306'
    networks:
      - app-network
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      interval: 30s
      retries: 5
      start_period: 10s
      timeout: 10s

  app:
    build: .
    container_name: node_app
    volumes:
      - ./src:/app/src
      - ./dist:/app/dist
    depends_on:
      - mysql
    ports:
      - '8000:3000'
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data: # Định nghĩa volume mysql_data tại đây để không bị lỗi
